// Package skills is the discovery + filtering + system-prompt-injection
// layer for skill files. A skill is a directory containing a SKILL.md
// with YAML frontmatter (name, description, optional agents) and an
// optional skill.toml sidecar with managed metadata (version, status,
// scoping, provenance).
//
// Selective port from `_impl_docs/ref/springdrift/src/skills.gleam`.
// The port is faithful on shape — same SkillMeta fields, same
// frontmatter parser semantics, same skill.toml-wins precedence,
// same for_agent / for_context filter semantics with the `all` and
// `all_specialists` special tokens, same XML rendering for
// `<available_skills>`. Token-cost estimation uses the same
// chars/4 ratio.
//
// Deferred (per the doc/roadmap/shipped/identity-skills-preamble-port
// reference, tier 2+):
//   - Domain-extraction integration (for_context's query_domains
//     comes from intent extraction in the cycle context; we pass
//     empty domains today which means context-scoped skills inject
//     unconditionally).
//   - Skill metrics (append_inject + per-skill JSONL of read/inject
//     events) — depends on a skills-metrics store we don't have.
//   - Auto-generated skills with `derived_from` CBR case IDs —
//     depends on the skills lifecycle subsystem.
//
// The reference doc enumerates every Springdrift surface; this
// package ports the load-bearing core for Tier 1.
package skills

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

// SkillMdFilename is the canonical body file name. Discovery looks for
// <dir>/<entry>/SKILL.md and the safe-path check on read_skill
// requires the path to end with this exact name.
const SkillMdFilename = "SKILL.md"

// SkillTomlFilename is the optional sidecar file. When present its
// fields override the SKILL.md frontmatter on overlapping keys.
const SkillTomlFilename = "skill.toml"

// CharsPerToken is the rough chars-to-tokens ratio used for the
// `token_cost_estimate` field. Matches Springdrift's value exactly.
// Informational only — never gates behaviour.
const CharsPerToken = 4

// SkillStatus discriminates active skills (eligible for injection)
// from archived skills (kept on disk for audit, not surfaced).
type SkillStatus string

const (
	StatusActive   SkillStatus = "active"
	StatusArchived SkillStatus = "archived"
)

// SkillAuthorKind discriminates the three author types Springdrift
// supports. Operator is the human; System is auto-generated by the
// platform (e.g. defaults shipped with the binary); Agent is a skill
// the agent itself proposed (and the safety gate accepted).
type SkillAuthorKind string

const (
	AuthorOperator SkillAuthorKind = "operator"
	AuthorSystem   SkillAuthorKind = "system"
	AuthorAgent    SkillAuthorKind = "agent"
)

// SkillAuthor records who created a skill. AgentName + CycleID are
// only meaningful when Kind == AuthorAgent.
type SkillAuthor struct {
	Kind     SkillAuthorKind
	AgentName string
	CycleID   string
}

// SkillMeta is one discovered skill. Mirrors Springdrift's SkillMeta
// record exactly. The body is NOT included — read_skill loads it on
// demand from `Path`.
type SkillMeta struct {
	// ID is the directory name by default; skill.toml can override.
	ID string
	// Name is the human-readable title from frontmatter or skill.toml.
	Name string
	// Description is what the cog's LLM sees on the
	// <available_skills> XML; it picks skills by reading this.
	Description string
	// Path is the absolute file path to SKILL.md.
	Path string
	// Version defaults to 1; bumped via skill.toml.
	Version int
	// Status defaults to Active.
	Status SkillStatus
	// Agents scopes the skill. Empty = legacy "all" semantics
	// (frontmatter-only skills); explicit list filters by name with
	// special tokens "all" (any agent) and "all_specialists" (any
	// non-cognitive agent).
	Agents []string
	// Contexts scopes by domain tag. Empty = always inject (no
	// filter); "all" = always inject; otherwise injected when at
	// least one context tag matches an active query domain.
	Contexts []string
	// TokenCostEstimate is body chars / CharsPerToken. Informational.
	TokenCostEstimate int
	// Author defaults to Operator when unspecified.
	Author SkillAuthor
	// CreatedAt / UpdatedAt are ISO-8601 timestamps; empty when
	// unknown.
	CreatedAt string
	UpdatedAt string
	// DerivedFrom names the CBR case(s) the skill was generated
	// from for auto-generated skills. Empty for human-authored.
	DerivedFrom string
}

// Discover walks each directory looking for entry/SKILL.md files.
// Optionally merges a skill.toml sidecar from the same directory
// (sidecar fields override frontmatter on conflict). Skills whose
// frontmatter doesn't parse are silently dropped — discovery is
// best-effort.
//
// Each path is tilde-expanded (~/foo → $HOME/foo) before reading.
// Directories that don't exist are skipped without error so an
// optional ~/.config/retainer/skills doesn't crash discovery when
// the user has no global config.
func Discover(dirs []string) []SkillMeta {
	var out []SkillMeta
	for _, dir := range dirs {
		expanded := ExpandTilde(dir)
		entries, err := os.ReadDir(expanded)
		if err != nil {
			// Missing skills dirs are normal (e.g. global config).
			// Anything else gets the same silent-skip — discover is
			// best-effort.
			continue
		}
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			entryDir := filepath.Join(expanded, entry.Name())
			skillPath := filepath.Join(entryDir, SkillMdFilename)
			body, err := os.ReadFile(skillPath)
			if err != nil {
				continue
			}
			fmName, fmDesc, fmAgents, ok := parseFrontmatter(string(body))
			if !ok {
				// Malformed frontmatter — skip silently.
				continue
			}
			tomlPath := filepath.Join(entryDir, SkillTomlFilename)
			tomlData, _ := os.ReadFile(tomlPath) // err = no sidecar
			meta := mergeSkill(entry.Name(), skillPath, string(body),
				fmName, fmDesc, fmAgents, tomlData)
			out = append(out, meta)
		}
	}
	// Stable order so XML rendering and tests are deterministic.
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// ForAgent filters skills to those scoped for the given agent name.
// Mirrors Springdrift's for_agent semantics:
//
//   - Empty agents list → match (legacy frontmatter "all").
//   - Explicit list contains agentName → match.
//   - Contains "all" → match for any agent.
//   - Contains "all_specialists" → match for any non-"cognitive" agent.
//
// The cog passes "cognitive" when assembling its own prompt;
// specialist agents pass their own name.
func ForAgent(in []SkillMeta, agentName string) []SkillMeta {
	isSpecialist := agentName != "cognitive"
	out := in[:0:0]
	for _, s := range in {
		if len(s.Agents) == 0 {
			out = append(out, s)
			continue
		}
		matched := false
		for _, a := range s.Agents {
			if a == agentName || a == "all" {
				matched = true
				break
			}
			if isSpecialist && a == "all_specialists" {
				matched = true
				break
			}
		}
		if matched {
			out = append(out, s)
		}
	}
	return out
}

// ForContext filters skills to those whose context tags overlap
// queryDomains. Empty contexts list = always inject (no filter).
// Contains "all" = always inject. Otherwise: inject when at least
// one of the skill's contexts is in queryDomains.
//
// queryDomains comes from intent extraction in the cycle context;
// today the curator passes empty (matches Springdrift's stub
// behaviour) so context-scoped skills inject unconditionally.
func ForContext(in []SkillMeta, queryDomains []string) []SkillMeta {
	out := in[:0:0]
	for _, s := range in {
		if len(s.Contexts) == 0 {
			out = append(out, s)
			continue
		}
		matched := false
		for _, c := range s.Contexts {
			if c == "all" {
				matched = true
				break
			}
			for _, q := range queryDomains {
				if c == q {
					matched = true
					break
				}
			}
			if matched {
				break
			}
		}
		if matched {
			out = append(out, s)
		}
	}
	return out
}

// ToSystemPromptXML renders skills as the <available_skills> block
// the cog injects into the system prompt. Empty input returns "" so
// callers don't need a special-case branch when no skills are
// configured.
//
// Output shape exactly matches Springdrift's `to_system_prompt_xml`:
//
//	<available_skills>
//	  <skill>
//	    <name>web-research</name>
//	    <description>Search and extraction strategy</description>
//	    <location>/path/to/SKILL.md</location>
//	  </skill>
//	  ...
//	</available_skills>
//
// Special XML characters (& < > " ') in name/description/location
// are escaped so the block parses cleanly when surfaced to the LLM.
func ToSystemPromptXML(skills []SkillMeta) string {
	if len(skills) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("<available_skills>\n")
	for i, s := range skills {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "  <skill>\n")
		fmt.Fprintf(&b, "    <name>%s</name>\n", xmlEscape(s.Name))
		fmt.Fprintf(&b, "    <description>%s</description>\n", xmlEscape(s.Description))
		fmt.Fprintf(&b, "    <location>%s</location>\n", xmlEscape(s.Path))
		fmt.Fprintf(&b, "  </skill>")
	}
	b.WriteString("\n</available_skills>")
	return b.String()
}

// EstimateTokenCost returns chars(body) / CharsPerToken. Used by the
// discovery merge step; safe to call on any string.
func EstimateTokenCost(body string) int {
	return len(body) / CharsPerToken
}

// ExpandTilde turns "~/foo" into "$HOME/foo" using os.UserHomeDir;
// returns the input unchanged when it doesn't begin with "~/" or
// when the home lookup fails (defensive — discovery falls back to
// "skip directory" when the path doesn't exist anyway).
func ExpandTilde(path string) string {
	if !strings.HasPrefix(path, "~/") {
		return path
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return path
	}
	return filepath.Join(home, path[2:])
}

// ---------------------------------------------------------------------------
// Frontmatter parsing
// ---------------------------------------------------------------------------

// parseFrontmatter extracts name, description, and agents from the
// `---`-fenced YAML-ish header. Required: name, description.
// Optional: agents (comma-separated).
//
// The format is intentionally narrow — single-line `key: value`
// pairs only. Multiline YAML scalars (`description: >\n  ...`) are
// not supported in V1; skills using that style fall through to
// "frontmatter unparseable, skip skill." The reference doc lists
// this as a known limitation and the embedded starter skills avoid
// the multiline form.
func parseFrontmatter(content string) (name, desc string, agents []string, ok bool) {
	body := content
	// Strip leading "---\n" fence if present.
	if strings.HasPrefix(body, "---\n") {
		body = body[4:]
	}
	// Take everything before the closing "\n---" fence.
	if i := strings.Index(body, "\n---"); i >= 0 {
		body = body[:i]
	}
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		idx := strings.Index(line, ":")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		value := strings.TrimSpace(line[idx+1:])
		switch key {
		case "name":
			name = value
		case "description":
			desc = value
		case "agents":
			for _, a := range strings.Split(value, ",") {
				a = strings.TrimSpace(a)
				if a != "" {
					agents = append(agents, a)
				}
			}
		}
	}
	if name == "" || desc == "" {
		return "", "", nil, false
	}
	return name, desc, agents, true
}

// ---------------------------------------------------------------------------
// skill.toml sidecar
// ---------------------------------------------------------------------------

// tomlOverrides mirrors Springdrift's `TomlOverrides` record. Each
// field is a pointer so we can distinguish "field absent" from
// "field set to zero value" — important for the agents default
// (omitted ↔ "use frontmatter agents"; explicit empty array would
// be invalid).
type tomlOverrides struct {
	id           *string
	name         *string
	description  *string
	version      *int
	status       *SkillStatus
	agents       *[]string
	contexts     *[]string
	author       *SkillAuthor
	createdAt    *string
	updatedAt    *string
	derivedFrom  *string
	hasAnyField bool
}

func parseSkillToml(data []byte) (tomlOverrides, error) {
	var raw struct {
		ID          string `toml:"id"`
		Name        string `toml:"name"`
		Description string `toml:"description"`
		Version     int    `toml:"version"`
		Status      string `toml:"status"`
		Scoping     struct {
			Agents   []string `toml:"agents"`
			Contexts []string `toml:"contexts"`
		} `toml:"scoping"`
		Provenance struct {
			Author      string `toml:"author"`
			AgentName   string `toml:"agent_name"`
			CycleID     string `toml:"cycle_id"`
			CreatedAt   string `toml:"created_at"`
			UpdatedAt   string `toml:"updated_at"`
			DerivedFrom string `toml:"derived_from"`
		} `toml:"provenance"`
	}
	if err := toml.Unmarshal(data, &raw); err != nil {
		return tomlOverrides{}, err
	}
	var out tomlOverrides
	if raw.ID != "" {
		out.id = &raw.ID
		out.hasAnyField = true
	}
	if raw.Name != "" {
		out.name = &raw.Name
		out.hasAnyField = true
	}
	if raw.Description != "" {
		out.description = &raw.Description
		out.hasAnyField = true
	}
	if raw.Version != 0 {
		out.version = &raw.Version
		out.hasAnyField = true
	}
	if raw.Status != "" {
		s := statusFromString(raw.Status)
		out.status = &s
		out.hasAnyField = true
	}
	if raw.Scoping.Agents != nil {
		out.agents = &raw.Scoping.Agents
		out.hasAnyField = true
	}
	if raw.Scoping.Contexts != nil {
		out.contexts = &raw.Scoping.Contexts
		out.hasAnyField = true
	}
	if raw.Provenance.Author != "" {
		author := SkillAuthor{
			Kind:      authorKindFromString(raw.Provenance.Author),
			AgentName: raw.Provenance.AgentName,
			CycleID:   raw.Provenance.CycleID,
		}
		out.author = &author
		out.hasAnyField = true
	}
	if raw.Provenance.CreatedAt != "" {
		out.createdAt = &raw.Provenance.CreatedAt
		out.hasAnyField = true
	}
	if raw.Provenance.UpdatedAt != "" {
		out.updatedAt = &raw.Provenance.UpdatedAt
		out.hasAnyField = true
	}
	if raw.Provenance.DerivedFrom != "" {
		out.derivedFrom = &raw.Provenance.DerivedFrom
		out.hasAnyField = true
	}
	return out, nil
}

func statusFromString(s string) SkillStatus {
	if strings.EqualFold(s, "archived") {
		return StatusArchived
	}
	// Unknown values map to Active so a malformed status never
	// silently archives a skill.
	return StatusActive
}

func authorKindFromString(s string) SkillAuthorKind {
	switch strings.ToLower(s) {
	case "system":
		return AuthorSystem
	case "agent":
		return AuthorAgent
	default:
		return AuthorOperator
	}
}

// ---------------------------------------------------------------------------
// Discovery merge — combines frontmatter + sidecar + sensible defaults
// ---------------------------------------------------------------------------

// mergeSkill produces a SkillMeta from frontmatter + optional
// skill.toml. The merge rules mirror Springdrift's `merge_skill`:
//
//   - Defaults: ID=dirName, Version=1, Status=Active, Author=Operator,
//     no CreatedAt/UpdatedAt/DerivedFrom.
//   - When skill.toml has any field set, its agents default
//     becomes ["cognitive"] (conservative — opposite of frontmatter's
//     "all" default) UNLESS the toml explicitly sets agents.
func mergeSkill(dirName, path, body, fmName, fmDesc string, fmAgents []string, tomlData []byte) SkillMeta {
	id := dirName
	name := fmName
	description := fmDesc
	agents := fmAgents
	version := 1
	status := StatusActive
	contexts := []string(nil)
	author := SkillAuthor{Kind: AuthorOperator}
	createdAt := ""
	updatedAt := ""
	derivedFrom := ""

	var toml tomlOverrides
	if len(tomlData) > 0 {
		parsed, err := parseSkillToml(tomlData)
		if err == nil {
			toml = parsed
		}
	}

	if toml.id != nil {
		id = *toml.id
	}
	if toml.name != nil {
		name = *toml.name
	}
	if toml.description != nil {
		description = *toml.description
	}
	if toml.version != nil {
		version = *toml.version
	}
	if toml.status != nil {
		status = *toml.status
	}
	// Springdrift's agents-default rule: if the sidecar file is
	// present (any field set) but didn't specify agents, default to
	// ["cognitive"] — the conservative "cog only" scoping.
	switch {
	case toml.agents != nil:
		agents = *toml.agents
	case toml.hasAnyField && len(fmAgents) == 0:
		agents = []string{"cognitive"}
	}
	if toml.contexts != nil {
		contexts = *toml.contexts
	}
	if toml.author != nil {
		author = *toml.author
	}
	if toml.createdAt != nil {
		createdAt = *toml.createdAt
	}
	if toml.updatedAt != nil {
		updatedAt = *toml.updatedAt
	}
	if toml.derivedFrom != nil {
		derivedFrom = *toml.derivedFrom
	}

	return SkillMeta{
		ID:                id,
		Name:              name,
		Description:       description,
		Path:              path,
		Version:           version,
		Status:            status,
		Agents:            agents,
		Contexts:          contexts,
		TokenCostEstimate: EstimateTokenCost(body),
		Author:            author,
		CreatedAt:         createdAt,
		UpdatedAt:         updatedAt,
		DerivedFrom:       derivedFrom,
	}
}

// ---------------------------------------------------------------------------
// XML escaping
// ---------------------------------------------------------------------------

func xmlEscape(s string) string {
	r := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&apos;",
	)
	return r.Replace(s)
}

// ---------------------------------------------------------------------------
// Read + safe-path check
// ---------------------------------------------------------------------------

// ErrPathInvalid is returned by ReadBody / IsSafePath when the given
// path doesn't end in /SKILL.md, doesn't resolve under one of the
// configured skills_dirs, or doesn't exist.
var ErrPathInvalid = errors.New("skills: path is not a safe SKILL.md inside a configured skills directory")

// ReadBody reads the body of a SKILL.md file after validating the
// path against the same safety rules as IsSafePath. Used by the
// `read_skill` tool: we don't trust the LLM's claim that the path is
// safe — every read goes through this gate.
func ReadBody(path string, skillsDirs []string) (string, error) {
	if err := IsSafePath(path, skillsDirs); err != nil {
		return "", err
	}
	body, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("skills: read %s: %w", path, err)
	}
	return string(body), nil
}

// IsSafePath validates that path:
//  1. ends with /SKILL.md (suffix check, case-sensitive)
//  2. exists and is a regular file
//  3. resolves (via symlink expansion) to a location inside one of
//     the configured skills_dirs (so a SKILL.md symlink to /etc/passwd
//     is rejected)
//
// Returns nil when safe, ErrPathInvalid wrapped with detail otherwise.
// Mirrors Springdrift's tools/builtin.is_safe_skill_path.
func IsSafePath(path string, skillsDirs []string) error {
	if !strings.HasSuffix(path, string(os.PathSeparator)+SkillMdFilename) {
		return fmt.Errorf("%w: must end with /%s", ErrPathInvalid, SkillMdFilename)
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		// Path doesn't exist or symlink chain broken.
		return fmt.Errorf("%w: %v", ErrPathInvalid, err)
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return fmt.Errorf("%w: stat: %v", ErrPathInvalid, err)
	}
	if info.Mode()&fs.ModeType != 0 {
		return fmt.Errorf("%w: not a regular file", ErrPathInvalid)
	}
	for _, dir := range skillsDirs {
		expanded := ExpandTilde(dir)
		canonicalDir, err := filepath.EvalSymlinks(expanded)
		if err != nil {
			// Configured dir missing — skip; not an error here.
			continue
		}
		// Add trailing separator so /a/b doesn't match /a/bcd by
		// prefix.
		if !strings.HasSuffix(canonicalDir, string(os.PathSeparator)) {
			canonicalDir += string(os.PathSeparator)
		}
		if strings.HasPrefix(resolved, canonicalDir) {
			return nil
		}
	}
	return fmt.Errorf("%w: resolved path %q is not inside any configured skills directory", ErrPathInvalid, resolved)
}
